/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkspaceRouteImport } from './routes/ai-workspace'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceRoute = AiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/customers': typeof CustomersIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-workspace'
    | '/customers/$customerId'
    | '/tickets/$ticketId'
    | '/customers/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-workspace'
    | '/customers/$customerId'
    | '/tickets/$ticketId'
    | '/customers'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/ai-workspace'
    | '/customers/$customerId'
    | '/tickets/$ticketId'
    | '/customers/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkspaceRoute: typeof AiWorkspaceRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace': {
      id: '/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkspaceRoute: AiWorkspaceRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
